version: '3.3'

services:
  ui:
    image: noma/ui
    container_name: ui.noma.io
    environment:
      - VIRTUAL_PORT=3000
      - NODE_ENV=local
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./build/noma/ui/.dockerfile
    volumes:
      - ./ui:/noma/io/ui
    networks:
      - network

  www:
    image: noma/www
    container_name: www.noma.io
    environment:
      - VIRTUAL_PORT=3001
      - NODE_ENV=local
    ports:
      - 3001:3001
    build:
      context: .
      dockerfile: ./build/noma/www/.dockerfile
    volumes:
      - ./www:/noma/io/www
    networks:
      - network

  api:
    image: noma/api
    container_name: api.noma.io
    environment:
      - VIRTUAL_PORT=3002
      - NODE_ENV=local
    ports:
      - 3002:3002
    build:
      context: .
      dockerfile: ./build/noma/api/.dockerfile
    volumes:
      - ./api:/noma/io/api
    networks:
      - network

volumes:
  cache:
  database:
  raygun-agent:
  proxy.encrypt:
  proxy.certificates:
  proxy.challenge:
  proxy.parameters:
  #search:

networks:
  network: